version: "3.8"

services:
  mysql:
    image: mysql:8.0.32
    restart: "always"
    environment:
      MYSQL_DATABASE: 'aws-starter'
      MYSQL_ROOT_PASSWORD: 'aws-starter-pass'
    ports:
      - '3306:3306'
    expose:
      - '3306'